version: "2"

services:
  gitlab:
    build:
      context: ./gitlab-ce
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        user['uid'] = 998
        user['gid'] = 998
        gitlab_rails['time_zone'] = 'Asia/Tokyo'

  redmine:
    build:
      context: ./redmine
    ports:
      - "10081:3000"
    volumes:
      - redmine-files:/usr/src/redmine/files
    volumes_from:
      - gitlab
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: example
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - redmine-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: example

volumes:
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local
  redmine-files:
    driver: local
  redmine-data:
    driver: local
