version: "2"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "10080:80"
      - "10443:443"
      - "10022:22"
    volumes:
      - config:/etc/gitlab
      - logs:/var/log/gitlab
      - data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |

  redmine:
    image: redmine:latest
    ports:
      - "10081:3000"
    volumes:
      - redmine-files:/usr/src/redmine/files
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: example
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    volumes:
      - redmine-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: example

volumes:
  config:
    driver: local
  logs:
    driver: local
  data:
    driver: local
  redmine-files:
    driver: local
  redmine-data:
    driver: local
